### PR TITLE
Splitting main.py into some files

### PR DESCRIPTION
**Pull request by kallejre**
Creating PR draft so you'd have idea what i have been doing past few week and won't create huge commit conflict.
This PR starts addressing #14 in attempt to split functions into separate files. sadly this seems to kill git's blame functionality. Mostly maintenance activities such as cut-past and standardizing some utility functions. Regex inlines got small fixes for example. 

Big new feature is colors-loader that is meant to be used in future to add support for `*:colour:*` tags to the renderer. Covers about 3000 most popular colours used in OSM.

I have no idea if all this still works. Therefore I'm opening this PR draft with ~~a request not to pull~~ maintainer edit access to let you fix errors there may come across.

### CODE REVIEW

**Comment by GoodClover** [comment]
What happened here?
This looks like it's going to mess up git greatly.
image

**Comment by GoodClover** [comment]
I'm not sure how good you are with `git`, but I'd appreciate it if you could make more descriptive commit comments.
With the amount of code being changed it becomes hard to navigate and understand.
(for example see my recent commits with a `…` button after them)

**Comment by kallejre** [comment]
> What happened here?  This looks like it's going to mess up git greatly.

There was 15-row lambda function used in two places for adding changeset and note discussion to embeddeds. I had separated them into little bit more generic named function [`format_discussions`](https://github.com/kallejre/OSM-Discord-bot/blob/main/utils.py#L134), but not committed it to git yet. Then you made a commit to change timestamp formatting in those lambda functions. As i had moved the lambdas to utils.py, git was unable to match the two versions and caused conflict, which couldn't be fixed with either github app nor website. I tried to manually copy portions of your commit into my version, but it didn't help either. I had to install new git software to fix that.

Git history is already pretty much unfixably messed up because history can't be rewritten, if there are merges involved. Is it possible to create new branch from your current and then move most commits there?

And then there's challenge of maintaining history while moving functions from one file to another.

**Comment by GoodClover** [comment]
> but not committed it to git yet. Then you made a commit to change timestamp formatting in those lambda functions.

This is why it's best to create smaller, more frequent PRs/commits, rather than one large one.

> Is it possible to create new branch from your current and then move most commits there?

What do you mean by this?

> And then there's challenge of maintaining history while moving functions from one file to another.

I'd looked into this before, it's impossible in most cases.
With the amount of code being changed, and our already messed up history, there's not much point in putting effort into it.

**Pull request closed without merging**
